document.writeln("<div class=\'menu\'>");
document.writeln("	<p class=\'houName\'>全橙网络公司</p>");
document.writeln("	<ul>");
document.writeln("		<a href=\'AAppointment_storeAppointment\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/edit.png\' class=\'menuImg\' />");
document.writeln("			<span>今日预约</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a href=\'AAppointment_storeAppointmentRecord\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/rolodex.png\' class=\'menuImg\' />");
document.writeln("			<span>预约历史</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a href=\'AUser_storeUser\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/user.png\' class=\'menuImg\'  />");
document.writeln("			<span>会员信息</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a href=\'AStore_storeSer\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/house.png\' class=\'menuImg\' />");
document.writeln("			<span>门店管理</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a href=\'ACoupon_storeCoupon\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/tag.png\' class=\'menuImg\'  />");
document.writeln("			<span>优惠券</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a href=\'AStore_lock\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/lock.png\' class=\'menuImg\'  />");
document.writeln("			<span>锁车位</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
//document.writeln("		<a href=\'guanggao.html\'>");
//document.writeln("		<li class=\'menuLi\'>");
//document.writeln("			<img src=\'img/ad.png\' class=\'menuImg\'  />");
//document.writeln("			<span>广告</span>");
//document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
//document.writeln("		</li>");
//document.writeln("		</a>");
document.writeln("	</ul>");
document.writeln("</div>");

//document.writeln("		<a href=\'adver.html\'>");
//document.writeln("		<li class=\'menuLi\'>");
//document.writeln("			<img src=\'img/user.png\' class=\'menuImg\'  />");
//document.writeln("			<span>添加广告</span>");
//document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
//document.writeln("		</li>");
//document.writeln("		</a>");
//document.writeln("	</ul>");
//document.writeln("</div>");