document.writeln("<div class=\'menu\'>");
document.writeln("	<ul>");
document.writeln("		<a id=\'companyManager\' href=\'ACompany_companyManager\'>");
document.writeln("		<li class=\'menuLi\' sta=\'sjgl\'>");
document.writeln("			<img src=\'img/house.png\' class=\'menuImg\' />");
document.writeln("			<span>商家管理</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a id=\'accountManager\' href=\'ACompany_accountManager\'>");
document.writeln("		<li class=\'menuLi\' sta=\'zhgl\'>");
document.writeln("			<img src=\'img/rolodex.png\' class=\'menuImg\' />");
document.writeln("			<span>账号管理</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a id=\'adminManager\' href=\'Admin_adminManager\'>");
document.writeln("		<li class=\'menuLi\' sta=\'gly\'>");
document.writeln("			<img src=\'img/user.png\' class=\'menuImg\'  />");
document.writeln("			<span>管理员</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a id=\'advertManager\' href=\'AAdvert_advertManager\'>");
document.writeln("		<li class=\'menuLi\' sta=\'ggw\'>");
document.writeln("			<img src=\'img/ad.png\' class=\'menuImg\' />");
document.writeln("			<span>广告位</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");

document.writeln("	</ul>");
document.writeln("</div>");

//document.writeln("		<a href=\'adver.html\'>");
//document.writeln("		<li class=\'menuLi\'>");
//document.writeln("			<img src=\'img/user.png\' class=\'menuImg\'  />");
//document.writeln("			<span>添加广告</span>");
//document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
//document.writeln("		</li>");
//document.writeln("		</a>");
//document.writeln("	</ul>");
//document.writeln("</div>");