document.writeln("<div class=\'menu\'>");
document.writeln("	<p class=\'houName\'>全橙网络公司</p>");
document.writeln("	<ul>");
document.writeln("		<a href=\'AAppointment_companyAppointment\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/edit.png\' class=\'menuImg\' />");
document.writeln("			<span>今日预约</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a href=\'AAppointment_companyAppointRecord\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/rolodex.png\' class=\'menuImg\' />");
document.writeln("			<span>预约历史</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a href=\'AUser_companyUser\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/user.png\' class=\'menuImg\'  />");
document.writeln("			<span>会员信息</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a href=\'AStore_companyStore\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/house.png\' class=\'menuImg\' />");
document.writeln("			<span>门店管理</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
document.writeln("		<a href=\'AStore_companyStoreSer\'>");
document.writeln("		<li class=\'menuLi\'>");
document.writeln("			<img src=\'img/house.png\' class=\'menuImg\' />");
document.writeln("			<span>门店服务</span>");
document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
document.writeln("		</li>");
document.writeln("		</a>");
//document.writeln("		<a href=\'adminManager.html\'>");
//document.writeln("		<li class=\'menuLi\'>");
//document.writeln("			<img src=\'img/users.png\' class=\'menuImg\'  />");
//document.writeln("			<span>管理员</span>");
//document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
//document.writeln("		</li>");
//document.writeln("		</a>");
//document.writeln("		<a href=\'addAdmin.html\'>");
//document.writeln("		<li class=\'menuLi\'>");
//document.writeln("			<img src=\'img/user.png\' class=\'menuImg\'  />");
//document.writeln("			<span>添加会员</span>");
//document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
//document.writeln("		</li>");
//document.writeln("		</a>");
//document.writeln("		<a href=\'guanggao.html\'>");
//document.writeln("		<li class=\'menuLi\'>");
//document.writeln("			<img src=\'img/ad.png\' class=\'menuImg\'  />");
//document.writeln("			<span>广告</span>");
//document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
//document.writeln("		</li>");
//document.writeln("		</a>");
document.writeln("	</ul>");
document.writeln("</div>");

//document.writeln("		<a href=\'adver.html\'>");
//document.writeln("		<li class=\'menuLi\'>");
//document.writeln("			<img src=\'img/user.png\' class=\'menuImg\'  />");
//document.writeln("			<span>添加广告</span>");
//document.writeln("			<img src=\'img/arrow.png\' class=\'menuArrow\'/>");
//document.writeln("		</li>");
//document.writeln("		</a>");
//document.writeln("	</ul>");
//document.writeln("</div>");